# Generated by Django 3.1.3 on 2020-11-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='견과류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='곡물전분류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='기타',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='김치류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='난류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='면류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='버섯류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='유제품',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='육류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='조리가공품류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='조미료',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='채소류',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='해산물',
            field=models.IntegerField(default=0),
        ),
    ]
