# Generated by Django 3.1.3 on 2020-11-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20201110_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('food_1', models.IntegerField(default=-1)),
                ('food_2', models.IntegerField(default=-1)),
                ('food_3', models.IntegerField(default=-1)),
                ('food_4', models.IntegerField(default=-1)),
                ('food_5', models.IntegerField(default=-1)),
                ('food_6', models.IntegerField(default=-1)),
                ('food_7', models.IntegerField(default=-1)),
            ],
        ),
    ]
