# Generated by Django 3.1.3 on 2020-11-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_user_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_history',
            name='name',
        ),
        migrations.AddField(
            model_name='user_history',
            name='user_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
