# Generated by Django 3.1.3 on 2020-11-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20201111_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='user_num',
            field=models.IntegerField(default=-1),
        ),
    ]
