# Generated by Django 3.1.3 on 2020-11-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_auto_20201111_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='food_1',
            field=models.CharField(default='-1', max_length=200),
        ),
    ]
