# Generated by Django 3.1.3 on 2020-11-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_auto_20201111_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='food_1',
            field=models.CharField(default='f', max_length=200),
        ),
    ]
