# Generated by Django 3.1.3 on 2020-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_auto_20201112_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='food_1',
            field=models.CharField(default='f', max_length=500),
        ),
        migrations.AlterField(
            model_name='user_history',
            name='food_2',
            field=models.CharField(default='-1', max_length=500),
        ),
    ]
